name: Run Telegram Stock Bot

on:
  schedule:
    - cron: '0 18 * * *' # UTC time (jam 8 pagi WIB)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run bot script
        run: node index.js
